FROM alpine:3.3
LABEL works.weave.role=system
COPY ./a8routing /usr/bin/a8routing
RUN apk add --no-cache curl
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
ENTRYPOINT ["/usr/bin/a8routing"]
